<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<!-- MSBuild Dependencies -->
	<ItemGroup>
		<PackageReference Include="KSPBuildTools" Version="1.1.1"/>
	</ItemGroup>

	<!-- Static Properties -->
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>8</LangVersion>
		<AssemblyName>SunLock</AssemblyName>
		<KSPBT_ModPluginFolder>\Plugin</KSPBT_ModPluginFolder>
		<Configurations>Debug;Release;Unity</Configurations>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DefineConstants>DEBUG;TRACE;ENABLE_PROFILER</DefineConstants>
		<DebugType>portable</DebugType>
	</PropertyGroup>
</Project>
